name:                higher-level-async
version:             0.1.0.0
github:              "jborkowski/higher-level-async"
license:             BSD3
author:              "Jonatan Borkowski"
maintainer:          "jonatanborkowski@wp.pl"
copyright:           "2019 Jonatan Borkowski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jborkowski/higher-level-async#readme>

dependencies:
- async
- base >= 4.7 && < 5
- bytestring
- containers
- stm
- http-conduit
- network

library:
  source-dirs: src

executables:
  higher-level-async-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - higher-level-async

tests:
  higher-level-async-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - higher-level-async
